Alert when ruby stdlib not found

diff --git a/bin/ruby_index_tags b/bin/ruby_index_tags
--- a/bin/ruby_index_tags
+++ b/bin/ruby_index_tags
@@ -56,6 +56,8 @@ function index_stdlib {
 
     if [[ -n "$stdlib_dir" ]]; then
         index_dir "$stdlib_dir" "$temp_tags_file" "Ruby standard library"
+    else
+        echo "Ruby standard library not found!" 1>&2
     fi
 }
 
